CREATE TABLE dim_date (
  date_sk        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  full_date      DATE NOT NULL UNIQUE,
  year           NUMBER(4) NOT NULL,
  quarter        NUMBER(1) NOT NULL,
  month          NUMBER(2) NOT NULL,
  month_name     VARCHAR2(20) NOT NULL,
  day_of_month   NUMBER(2) NOT NULL,
  day_name       VARCHAR2(20) NOT NULL,
  is_weekend     NUMBER(1) NOT NULL
);

CREATE TABLE dim_customer (
  customer_sk           BIGSERIAL PRIMARY KEY,
  customer_unique_id    VARCHAR(50) NOT NULL,

  name                  VARCHAR(100),
  gender                CHAR(1),
  age                   INT,
  age_group             VARCHAR(20),
  phone                 VARCHAR(30),

  zip_code_prefix       VARCHAR(50),
  city                  VARCHAR(100),
  state                 CHAR(2),

  date_from             TIMESTAMP NOT NULL DEFAULT now(),
  date_to               TIMESTAMP NULL,
  is_current            BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE dim_seller (
  seller_sk             BIGSERIAL PRIMARY KEY,
  seller_id             VARCHAR(50) NOT NULL,

  zip_code_prefix       VARCHAR(50),
  city                  VARCHAR(100),
  state                 CHAR(2),

  date_from             TIMESTAMP NOT NULL DEFAULT now(),
  date_to               TIMESTAMP NULL,
  is_current            BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE dim_product (
  product_sk NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  product_id VARCHAR2(50) NOT NULL,

  product_category_name VARCHAR2(100),
  product_category_name_english VARCHAR2(100),
  product_weight_g NUMBER,
  product_length_cm NUMBER,
  product_height_cm NUMBER,
  product_width_cm NUMBER
);


CREATE TABLE dim_order (
  order_sk NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id VARCHAR2(50) NOT NULL,

  purchase_date_key  NUMBER NOT NULL,
  approved_date_key  NUMBER,
  carrier_date_key   NUMBER,
  delivered_date_key NUMBER,
  estimated_date_key NUMBER,

  order_status VARCHAR2(20) NOT NULL UNIQUE,

  CONSTRAINT fk_dim_order_purchase_date
    FOREIGN KEY (purchase_date_key) REFERENCES dim_date(date_sk),

  CONSTRAINT fk_dim_order_approved_date
    FOREIGN KEY (approved_date_key) REFERENCES dim_date(date_sk),

  CONSTRAINT fk_dim_order_carrier_date
    FOREIGN KEY (carrier_date_key) REFERENCES dim_date(date_sk),

  CONSTRAINT fk_dim_order_delivered_date
    FOREIGN KEY (delivered_date_key) REFERENCES dim_date(date_sk),

  CONSTRAINT fk_dim_order_estimated_date
    FOREIGN KEY (estimated_date_key) REFERENCES dim_date(date_sk)
);




CREATE TABLE fact_order_item (
  order_item_sk          BIGSERIAL PRIMARY KEY,

  customer_sk            BIGINT NOT NULL REFERENCES dim_customer(customer_sk),
  order_sk               BIGINT NOT NULL REFERENCES dim_order(order_sk),
  product_sk             BIGINT NOT NULL REFERENCES dim_product(product_sk),
  seller_sk              BIGINT NOT NULL REFERENCES dim_seller(seller_sk),

  order_item_id          INT NOT NULL,

  price                  NUMERIC NOT NULL,
  price_bucket           VARCHAR(20),

  freight_value          NUMERIC NOT NULL,
  item_total_value       NUMERIC NOT NULL,

  is_weekend_purchase    BOOLEAN NOT NULL DEFAULT false,
  is_late_delivery       BOOLEAN NOT NULL DEFAULT false,

  CONSTRAINT uq_fact_order_item UNIQUE (order_sk, order_item_id)
);